### ISSUE TITLE
 FALCON doesn't work on test data (CENTOS)

### ISSUE THREAD

**Issue by a-velt** [gconcepcion/pb-assembly#2]
Hi all,

I installed the latest version of FALCON with your instructions, on my CENTOS server. I created a new conda environment and I used this conda to install FALCON with the command : _conda install pb-assembly_. This installation worked perfectly.

Then, I recovered the test data, and launched Falcon with your instructions : 

```
git clone https://github.com/cdunn2001/git-sym.git
git clone https://github.com/pb-cdunn/FALCON-examples.git
cd FALCON-examples
../git-sym/git-sym update run/greg200k-sv2
cd run/greg200k-sv2
fc_run fc_run.cfg
```

And I got the following error : 

> falcon-kit 1.2.2
> pypeflow 2.0.4
> [INFO]Setup logging from file "None".
> [INFO]$ lfs setstripe -c 12 /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2 >
> [INFO]Apparently '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2' is not in lustre filesystem, which is fine.
> [INFO]fc_run started with configuration fc_run.cfg
> [WARNING]Unexpected keys in input config: set(['ovlp_HPCTANmask_option'])
> [WARNING]Please supply a default for "njobs" (aka concurrency) in section [job.defaults]. For now, we will use 8
> [INFO]cfg=
> {
>   "General": {
>     "LA4Falcon_preload": false,
>     "avoid_text_file_busy": true,
>     "bestn": 12,
>     "dazcon": false,
>     "falcon_sense_greedy": false,
>     "falcon_sense_option": "--output-multi --min-cov-aln 4 --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 8",
>     "falcon_sense_skip_contained": false,
>     "fc_ovlp_to_graph_option": " --min_len 1",
>     "genome_size": "200000",
>     "input_fofn": "input.fofn",
>     "input_type": "raw",
>     "length_cutoff": "1000",
>     "length_cutoff_pr": "1",
>     "overlap_filtering_setting": "--max-diff 120 --max-cov 120 --min-cov 2 --n-core 8",
>     "ovlp_DBsplit_option": "-s100",
>     "ovlp_HPCTANmask_option": "-l500",
>     "ovlp_HPCdaligner_option": "-v -B128 -M24",
>     "ovlp_daligner_option": "-e.9 -l2500 -k24 -h1024 -w6 -s100",
>     "pa_DBdust_option": "",
>     "pa_DBsplit_option": "-a -x500 -s4",
>     "pa_HPCTANmask_option": "-l500",
>     "pa_HPCdaligner_option": "-v -B128 -M24",
>     "pa_REPmask_code": "0,300;0,300;0,300",
>     "pa_daligner_option": "-e.8 -l3200 -k18 -h480  -w8 -s100",
>     "pa_dazcon_option": "-j 4 -x -l 500",
>     "pa_fasta_filter_option": "streamed-median",
>     "seed_coverage": 20,
>     "skip_checks": false,
>     "target": "assembly"
>   },
>   "job.defaults": {
>     "NPROC": "4",
>     "job_type": "string",
>     "njobs": 8,
>     "pwatcher_type": "blocking",
>     "submit": "bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}",
>     "use_tmpdir": false
>   },
>   "job.step.asm": {
>     "NPROC": "32"
>   },
>   "job.step.cns": {
>     "NPROC": "8"
>   },
>   "job.step.da": {},
>   "job.step.la": {},
>   "job.step.pda": {},
>   "job.step.pla": {}
> }
> [INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
> [INFO]job_type='string', (default)job_defaults={'pwatcher_type': 'blocking', 'use_tmpdir': False, 'job_type': 'string', 'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}', 'NPROC': '4', 'njobs': 8}, use_tmpdir=False, squash=True, job_name_style=0
> [INFO]Setting max_jobs to 8; was None
> [INFO]Num unsatisfied: 2, graph: 2
> [INFO]About to submit: Node(0-rawreads/build)
> [INFO]Popen: 'bash -C /cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-P47d6213d776274.bash.stdout 2>| /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-P47d6213d776274.bash.stderr'
> [INFO](slept for another 0.0s -- another 1 loop iterations)
> [INFO](slept for another 0.3s -- another 2 loop iterations)
> [ERROR]Task Node(0-rawreads/build) failed with exit-code=1
> [ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
> [ERROR]ready: set([])
>         submitted: set([])
> [ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
> Traceback (most recent call last):
>   File "/cm/shared/apps/FALCON_10-09-2018/bin/fc_run", line 11, in <module>
>     load_entry_point('falcon-kit==1.2.2', 'console_scripts', 'fc_run')()
>   File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 724, in main
>     main1(argv[0], args.config, args.logger)
>   File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1
>     input_fofn_fn=input_fofn_fn,
>   File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 242, in run
>     dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
>   File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks
>     wf.refreshTargets()
>   File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
>     self._refreshTargets(updateFreq, exitOnFailure)
>   File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 361, in _refreshTargets
>     raise Exception(msg)
> Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])

Have you an idea about that ? 

Best,
Amandine

**Comment by gconcepcion** [comment]
The very first step building the database failed which points to an installation problem.

I need to see the contents of:

`/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-P47d6213d776274.bash.stderr`

**Comment by a-velt** [comment]
Here is the contents of the file : 

```
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-P47d6213d776274.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-P47d6213d776274.bash ]]

/bin/bash ${executable}
+ /bin/bash /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-P47d6213d776274.bash
+ '[' '!' -d /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build ']'
+ cd /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
export PATH=$PATH:/bin
+ export PATH=/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/sha
red/apps/pitchfork_test_mhsieh/pitchfork/deployment/bin/:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/slurm/14.03.0/sbin:/cm/shared/apps/slurm/14.03.0/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbin:/cm/local
/apps/cmd/bin:/cm/shared/apps/cmgui:/usr/lib64/qt-3.3/bin:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/circos-0.69-6/bin/:/cm/shared/apps/pindel/:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/apps/eclipse:/cm/sha
red/apps/pitchfork/bin:/cm/shared/apps/openmpi/open64/64/1.8.1/bin:/cm/shared/apps/openmpi/gcc/64/1.8.1/bin:/cm/shared/apps/bin:/cm/shared/apps/R-3.2.1/bin:/cm/shared/apps/samtools-1.2:/cm/shared/apps/bcftools-1.2:/cm/share
d/apps/netcdf/gcc/64/4.3.1.1/bin:/usr/lib/jvm/jre-1.7.0/bin/:/cm/shared/apps/scripts:/cm/shared/apps/FastQC:/cm/shared/apps/clustalw-2.1:/cm/shared/apps/ncbi-blast-2.2.28+/bin:/cm/shared/apps/sublime_text_3:/cm/shared/apps/
vcftools_0.1.12b/bin:/cm/shared/apps/pindel-master/src:/cm/shared/apps/bamtools/bin:/cm/shared/apps/bamtools/lib:/cm/shared/apps/kseq:/cm/shared/apps/delly/src:/cm/shared/apps/SVDetect/bin:/cm/shared/apps/bowtie2-2.3.3.1-li
nux-x86_64:/cm/shared/apps/tophat-2.0.11:/cm/shared/apps/cufflinks-2.2.1:/cm/shared/apps/velvet_1.2.10:/cm/shared/apps/exonerate-2.2.0/bin:/cm/shared/apps/kmergenie-1.6950:/cm/shared/apps/bedtools2-2.19.1/bin:/cm/shared/app
s/seqtools-4.23:/cm/shared/apps/sratoolkit.2.3.4-2/bin:/cm/shared/apps/bwa:/cm/shared/apps/idba-1.1.1/bin:/cm/shared/apps/CAP3:/cm/shared/apps/Platanus:/cm/shared/apps/SOAPdenovo/SOAPdenovo2-src-r240:/cm/shared/apps/SPAdes-
3.5.0/bin:/cm/shared/apps/quast-2.3:/cm/shared/apps/Price:/cm/shared/apps/cgal-0.9.6-beta:/cm/shared/apps/tigra-0.4.0:/cm/shared/apps/wgs-8.3rc2/Linux-amd64/bin:/cm/shared/apps/ePCR:/cm/shared/apps/hapsembler-2.21/bin:/cm/s
hared/apps/SOAPdenovo-Trans:/cm/shared/apps/censor-4.2.29/bin:/cm/shared/apps/blast-2.2.26/bin:/cm/shared/apps/HTSeq-0.6.1/scripts:/cm/shared/apps/delly/src/htslib:/cm/shared/apps/canu-1.2/Linux-amd64/bin:/cm/shared/apps/pr
oovread/bin:/cm/shared/apps/MEGA7:/cm/shared/apps/muscle3.8.31_i86linux64:/cm/shared/apps/gmap-2016-11-07/bin:/cm/shared/apps/lamp.x86_64-unknown-linux-gnu.REL_2_5/bin:/cm/shared/apps/htop-1.0.3:/cm/shared/apps/MUMmer3.23:/
cm/shared/apps/sabre/:/cm/shared/apps/trinityrnaseq-Trinity-v2.5.0:/cm/shared/apps/augustus-3.2.3/bin:/cm/shared/apps/augustus-3.2.3/scripts/:/cm/shared/apps/TransDecoder-TransDecoder-v5.0.2/:/cm/shared/apps/interproscan-5.
13-52.0/:/cm/shared/apps/seqtools-4.23/dotter:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/root/bin:/bin
+ PATH=/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/app
s/pitchfork_test_mhsieh/pitchfork/deployment/bin/:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/slurm/14.03.0/sbin:/cm/shared/apps/slurm/14.03.0/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbin:/cm/local/apps/c
md/bin:/cm/shared/apps/cmgui:/usr/lib64/qt-3.3/bin:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/circos-0.69-6/bin/:/cm/shared/apps/pindel/:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/apps/eclipse:/cm/shared/app
s/pitchfork/bin:/cm/shared/apps/openmpi/open64/64/1.8.1/bin:/cm/shared/apps/openmpi/gcc/64/1.8.1/bin:/cm/shared/apps/bin:/cm/shared/apps/R-3.2.1/bin:/cm/shared/apps/samtools-1.2:/cm/shared/apps/bcftools-1.2:/cm/shared/apps/
netcdf/gcc/64/4.3.1.1/bin:/usr/lib/jvm/jre-1.7.0/bin/:/cm/shared/apps/scripts:/cm/shared/apps/FastQC:/cm/shared/apps/clustalw-2.1:/cm/shared/apps/ncbi-blast-2.2.28+/bin:/cm/shared/apps/sublime_text_3:/cm/shared/apps/vcftool
s_0.1.12b/bin:/cm/shared/apps/pindel-master/src:/cm/shared/apps/bamtools/bin:/cm/shared/apps/bamtools/lib:/cm/shared/apps/kseq:/cm/shared/apps/delly/src:/cm/shared/apps/SVDetect/bin:/cm/shared/apps/bowtie2-2.3.3.1-linux-x86
_64:/cm/shared/apps/tophat-2.0.11:/cm/shared/apps/cufflinks-2.2.1:/cm/shared/apps/velvet_1.2.10:/cm/shared/apps/exonerate-2.2.0/bin:/cm/shared/apps/kmergenie-1.6950:/cm/shared/apps/bedtools2-2.19.1/bin:/cm/shared/apps/seqto
ols-4.23:/cm/shared/apps/sratoolkit.2.3.4-2/bin:/cm/shared/apps/bwa:/cm/shared/apps/idba-1.1.1/bin:/cm/shared/apps/CAP3:/cm/shared/apps/Platanus:/cm/shared/apps/SOAPdenovo/SOAPdenovo2-src-r240:/cm/shared/apps/SPAdes-3.5.0/b
in:/cm/shared/apps/quast-2.3:/cm/shared/apps/Price:/cm/shared/apps/cgal-0.9.6-beta:/cm/shared/apps/tigra-0.4.0:/cm/shared/apps/wgs-8.3rc2/Linux-amd64/bin:/cm/shared/apps/ePCR:/cm/shared/apps/hapsembler-2.21/bin:/cm/shared/a
pps/SOAPdenovo-Trans:/cm/shared/apps/censor-4.2.29/bin:/cm/shared/apps/blast-2.2.26/bin:/cm/shared/apps/HTSeq-0.6.1/scripts:/cm/shared/apps/delly/src/htslib:/cm/shared/apps/canu-1.2/Linux-amd64/bin:/cm/shared/apps/proovread
/bin:/cm/shared/apps/MEGA7:/cm/shared/apps/muscle3.8.31_i86linux64:/cm/shared/apps/gmap-2016-11-07/bin:/cm/shared/apps/lamp.x86_64-unknown-linux-gnu.REL_2_5/bin:/cm/shared/apps/htop-1.0.3:/cm/shared/apps/MUMmer3.23:/cm/shar
ed/apps/sabre/:/cm/shared/apps/trinityrnaseq-Trinity-v2.5.0:/cm/shared/apps/augustus-3.2.3/bin:/cm/shared/apps/augustus-3.2.3/scripts/:/cm/shared/apps/TransDecoder-TransDecoder-v5.0.2/:/cm/shared/apps/interproscan-5.13-52.0
/:/cm/shared/apps/seqtools-4.23/dotter:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/root/bin:/bin
cd /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build
+ cd /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build
/bin/bash task.sh
+ /bin/bash task.sh
2018-09-10 10:43:28,897 - root - DEBUG - Running "/cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/task.json"
2018-09-10 10:43:28,898 - root - DEBUG - Checking existence of '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/task.json' with timeout=60
2018-09-10 10:43:28,898 - root - DEBUG - Loading JSON from '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/task.json'
2018-09-10 10:43:28,899 - root - DEBUG - {u'bash_template_fn': u'template.sh',
 u'inputs': {u'config': u'/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/General_config.json',
             u'input_fofn': u'/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/input.fofn'},
 u'outputs': {u'db': u'raw_reads.db', u'length_cutoff': u'length_cutoff'},
 u'parameters': {u'pypeflow_mb': 4000,
                 u'pypeflow_nproc': 1,
                 u'topdir': u'../..'}}
2018-09-10 10:43:28,899 - root - DEBUG - CD: '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build' <- '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build'
2018-09-10 10:43:28,899 - root - DEBUG - Checking existence of u'/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/input.fofn' with timeout=60
2018-09-10 10:43:28,899 - root - DEBUG - Checking existence of u'/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/General_config.json' with timeout=60
2018-09-10 10:43:28,899 - root - DEBUG - CD: '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build' -> '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build'
2018-09-10 10:43:28,899 - root - CRITICAL - Error in /cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build/
task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 143, in run_cfg_in_tmpdir
    python_function_name = cfg['python_function']
KeyError: 'python_function'
+++ pwd
++ echo 'FAILURE. Running top in /cm/shared/apps/FALCON_10-09-2018/FALCON-examples/run/greg200k-sv2/0-rawreads/build (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get
diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real    0m0.644s
user    0m0.084s
sys     0m0.104s
+ finish
+ echo 'finish code: 1'
```

**Comment by gconcepcion** [comment]
Either you sourced the wrong FALCON environment, or the one you have is contaminated. You may have installed the new Bioconda pb-assembly recipe, but it's clear from the error message that there is an installed version of FALCON-integrate being used to run the example. 
 `/cm/shared/apps/FALCON-integrate/pypeFLOW/pypeflow/do_task.py`

Make sure you are sourcing the proper environment and make sure you are running from a clean shell

**Comment by a-velt** [comment]
Ok, I will check and keep you in touch. Thank you

**Comment by a-velt** [comment]
I don't understand because my $PATH is /cm/shared/apps/FALCON_10-09-2018/bin:/bin, which are my miniconda environement with only the FALCON installation, i'm sure. And the bin containing the minimum commands of linux (sed, ls, etc...). But, really I don't know why FALCON see "/cm/shared/apps/FALCON-integrate". So, I renamed this folder as "FALCON-integrateOLD" and "fc_run fc_run.cfg" works fine. Now, I launched : 
`fc_unzip.py fc_unzip.cfg`

And I got : 
```
falcon-unzip 1.1.2
falcon-kit 1.2.2
pypeflow 2.0.4
Traceback (most recent call last):
  File "/cm/shared/apps/FALCON_10-09-2018/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.1.2', 'console_scripts', 'fc_unzip.py')()
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 3, in <module>
    from .. import unzip
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 7, in <module>
    from .tasks import unzip as tasks_unzip
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 5, in <module>
    from .. import io
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/falcon_unzip/io.py", line 21, in <module>
    from pysam.libcalignmentfile import AlignmentFile#, AlignmentHeader
  File "/cm/shared/apps/FALCON_10-09-2018/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /cm/shared/apps/FALCON_10-09-2018/lib/././libcom_err.so.3: symbol k5_strerror_r, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
```

Have you an idea about that ? Thank you very much for your help.
Amandine

**Comment by gconcepcion** [comment]
I can't tell exactly what's going on w/ your install, but it's clear that you have alot of competing packages installed based on your $PATH variable:

```
+ PATH=/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON_10-09-2018/bin:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/app
s/pitchfork_test_mhsieh/pitchfork/deployment/bin/:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/slurm/14.03.0/sbin:/cm/shared/apps/slurm/14.03.0/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbin:/cm/local/apps/c
md/bin:/cm/shared/apps/cmgui:/usr/lib64/qt-3.3/bin:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/circos-0.69-6/bin/:/cm/shared/apps/pindel/:/cm/shared/apps/FALCON-integrate/fc_env/bin:/cm/shared/apps/eclipse:/cm/shared/app
s/pitchfork/bin:/cm/shared/apps/openmpi/open64/64/1.8.1/bin:/cm/shared/apps/openmpi/gcc/64/1.8.1/bin:/cm/shared/apps/bin:/cm/shared/apps/R-3.2.1/bin:/cm/shared/apps/samtools-1.2:/cm/shared/apps/bcftools-1.2:/cm/shared/apps/
netcdf/gcc/64/4.3.1.1/bin:/usr/lib/jvm/jre-1.7.0/bin/:/cm/shared/apps/scripts:/cm/shared/apps/FastQC:/cm/shared/apps/clustalw-2.1:/cm/shared/apps/ncbi-blast-2.2.28+/bin:/cm/shared/apps/sublime_text_3:/cm/shared/apps/vcftool
s_0.1.12b/bin:/cm/shared/apps/pindel-master/src:/cm/shared/apps/bamtools/bin:/cm/shared/apps/bamtools/lib:/cm/shared/apps/kseq:/cm/shared/apps/delly/src:/cm/shared/apps/SVDetect/bin:/cm/shared/apps/bowtie2-2.3.3.1-linux-x86
_64:/cm/shared/apps/tophat-2.0.11:/cm/shared/apps/cufflinks-2.2.1:/cm/shared/apps/velvet_1.2.10:/cm/shared/apps/exonerate-2.2.0/bin:/cm/shared/apps/kmergenie-1.6950:/cm/shared/apps/bedtools2-2.19.1/bin:/cm/shared/apps/seqto
ols-4.23:/cm/shared/apps/sratoolkit.2.3.4-2/bin:/cm/shared/apps/bwa:/cm/shared/apps/idba-1.1.1/bin:/cm/shared/apps/CAP3:/cm/shared/apps/Platanus:/cm/shared/apps/SOAPdenovo/SOAPdenovo2-src-r240:/cm/shared/apps/SPAdes-3.5.0/b
in:/cm/shared/apps/quast-2.3:/cm/shared/apps/Price:/cm/shared/apps/cgal-0.9.6-beta:/cm/shared/apps/tigra-0.4.0:/cm/shared/apps/wgs-8.3rc2/Linux-amd64/bin:/cm/shared/apps/ePCR:/cm/shared/apps/hapsembler-2.21/bin:/cm/shared/a
pps/SOAPdenovo-Trans:/cm/shared/apps/censor-4.2.29/bin:/cm/shared/apps/blast-2.2.26/bin:/cm/shared/apps/HTSeq-0.6.1/scripts:/cm/shared/apps/delly/src/htslib:/cm/shared/apps/canu-1.2/Linux-amd64/bin:/cm/shared/apps/proovread
/bin:/cm/shared/apps/MEGA7:/cm/shared/apps/muscle3.8.31_i86linux64:/cm/shared/apps/gmap-2016-11-07/bin:/cm/shared/apps/lamp.x86_64-unknown-linux-gnu.REL_2_5/bin:/cm/shared/apps/htop-1.0.3:/cm/shared/apps/MUMmer3.23:/cm/shar
ed/apps/sabre/:/cm/shared/apps/trinityrnaseq-Trinity-v2.5.0:/cm/shared/apps/augustus-3.2.3/bin:/cm/shared/apps/augustus-3.2.3/scripts/:/cm/shared/apps/TransDecoder-TransDecoder-v5.0.2/:/cm/shared/apps/interproscan-5.13-52.0
/:/cm/shared/apps/seqtools-4.23/dotter:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/root/bin:/bin
```

In comparison, this is what the PATH looks like in the environment when I run the testcase:
```
+ PATH=/home/UNIXHOME/gconcepcion/.conda/envs/pb-assembly/bin:/mnt/software/a/anaconda2/4.2.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/bin
```


Again, I recommend running the script from a clean environment. 
It seems probable that there isa line in your `.bashrc` or `.bash_profile` tripping things up.

**Comment by a-velt** [comment]
Thanks for your help, there was a bad path in /etc/profile.d which is loaded by default, which generated the problem. Everything works correctly :) 

Congratulations for having made an installation as easy compared to the first version of FALCON.

Best,
Amandine

**Comment by gconcepcion** [comment]
Great! Glad you figured it out. @pb-cdunn deserves credit for ease of use improvements.

Good luck assembling!
